# apps/api/wrangler.toml
name = "thunder-api"
main = "src/worker.ts"
compatibility_date = "2024-11-21"
workers_dev = true

[[kv_namespaces]]
binding = "THUNDER_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[vars]
API_BASE = "https://ddragon.leagueoflegends.com"
CORS_ORIGIN = "http://localhost:5173"
MOCK = "1"

[triggers]
crons = ["*/5 * * * *"] # 5분 마다 스냅샷/헬스
