# .github/workflows/lighthouse.yml
name: lighthouse
on:
  workflow_dispatch:
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - name: Lighthouse CI (local)
        run: npx -y @lhci/cli autorun || true
